name: Update CHANGELOG on Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update changelog
        shell: bash
        run: |
          mkdir -p docs
          touch docs/CHANGELOG.md

          {
            echo "## ${{ github.event.release.tag_name }} - ${{ github.event.release.published_at }}"
            echo ""
            printf '%s\n' "${{ github.event.release.body }}"
            echo ""
            cat docs/CHANGELOG.md
          } > temp.md

          mv temp.md docs/CHANGELOG.md

      - name: Commit and push
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add docs/CHANGELOG.md

          git diff --cached --quiet && exit 0

          git commit -m "chore: update changelog"

          git push origin HEAD:main
